# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import openarm_service_pb2 as openarm__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in openarm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenArmServiceStub(object):
    """OpenArm gRPC 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/openarm.OpenArmService/Initialize',
                request_serializer=openarm__service__pb2.InitializeRequest.SerializeToString,
                response_deserializer=openarm__service__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.GetLeftPosition = channel.unary_unary(
                '/openarm.OpenArmService/GetLeftPosition',
                request_serializer=openarm__service__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=openarm__service__pb2.GetPositionResponse.FromString,
                _registered_method=True)
        self.SetLeftPosition = channel.unary_unary(
                '/openarm.OpenArmService/SetLeftPosition',
                request_serializer=openarm__service__pb2.SetPositionRequest.SerializeToString,
                response_deserializer=openarm__service__pb2.SetPositionResponse.FromString,
                _registered_method=True)
        self.GetRightPosition = channel.unary_unary(
                '/openarm.OpenArmService/GetRightPosition',
                request_serializer=openarm__service__pb2.GetPositionRequest.SerializeToString,
                response_deserializer=openarm__service__pb2.GetPositionResponse.FromString,
                _registered_method=True)
        self.SetRightPosition = channel.unary_unary(
                '/openarm.OpenArmService/SetRightPosition',
                request_serializer=openarm__service__pb2.SetPositionRequest.SerializeToString,
                response_deserializer=openarm__service__pb2.SetPositionResponse.FromString,
                _registered_method=True)
        self.TestRun = channel.unary_unary(
                '/openarm.OpenArmService/TestRun',
                request_serializer=openarm__service__pb2.TestRunRequest.SerializeToString,
                response_deserializer=openarm__service__pb2.TestRunResponse.FromString,
                _registered_method=True)


class OpenArmServiceServicer(object):
    """OpenArm gRPC 服务定义
    """

    def Initialize(self, request, context):
        """初始化控制器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeftPosition(self, request, context):
        """获取左臂位置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLeftPosition(self, request, context):
        """设置左臂位置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRightPosition(self, request, context):
        """获取右臂位置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRightPosition(self, request, context):
        """设置右臂位置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRun(self, request, context):
        """测试运行
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenArmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=openarm__service__pb2.InitializeRequest.FromString,
                    response_serializer=openarm__service__pb2.InitializeResponse.SerializeToString,
            ),
            'GetLeftPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeftPosition,
                    request_deserializer=openarm__service__pb2.GetPositionRequest.FromString,
                    response_serializer=openarm__service__pb2.GetPositionResponse.SerializeToString,
            ),
            'SetLeftPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLeftPosition,
                    request_deserializer=openarm__service__pb2.SetPositionRequest.FromString,
                    response_serializer=openarm__service__pb2.SetPositionResponse.SerializeToString,
            ),
            'GetRightPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRightPosition,
                    request_deserializer=openarm__service__pb2.GetPositionRequest.FromString,
                    response_serializer=openarm__service__pb2.GetPositionResponse.SerializeToString,
            ),
            'SetRightPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRightPosition,
                    request_deserializer=openarm__service__pb2.SetPositionRequest.FromString,
                    response_serializer=openarm__service__pb2.SetPositionResponse.SerializeToString,
            ),
            'TestRun': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRun,
                    request_deserializer=openarm__service__pb2.TestRunRequest.FromString,
                    response_serializer=openarm__service__pb2.TestRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openarm.OpenArmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openarm.OpenArmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenArmService(object):
    """OpenArm gRPC 服务定义
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.OpenArmService/Initialize',
            openarm__service__pb2.InitializeRequest.SerializeToString,
            openarm__service__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeftPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.OpenArmService/GetLeftPosition',
            openarm__service__pb2.GetPositionRequest.SerializeToString,
            openarm__service__pb2.GetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLeftPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.OpenArmService/SetLeftPosition',
            openarm__service__pb2.SetPositionRequest.SerializeToString,
            openarm__service__pb2.SetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRightPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.OpenArmService/GetRightPosition',
            openarm__service__pb2.GetPositionRequest.SerializeToString,
            openarm__service__pb2.GetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRightPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.OpenArmService/SetRightPosition',
            openarm__service__pb2.SetPositionRequest.SerializeToString,
            openarm__service__pb2.SetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openarm.OpenArmService/TestRun',
            openarm__service__pb2.TestRunRequest.SerializeToString,
            openarm__service__pb2.TestRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
