# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openarm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openarm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15openarm_service.proto\x12\x07openarm\"<\n\x08Position\x12\x15\n\rarm_positions\x18\x01 \x03(\x01\x12\x19\n\x11gripper_positions\x18\x02 \x03(\x01\"\xa6\x01\n\x12SetPositionRequest\x12\x1c\n\x14\x61rm_target_positions\x18\x01 \x03(\x01\x12\x1f\n\x17gripper_target_position\x18\x02 \x01(\x01\x12\x1d\n\x15\x63urrent_arm_positions\x18\x03 \x03(\x01\x12 \n\x18\x63urrent_gripper_position\x18\x04 \x01(\x01\x12\x10\n\x08\x61rm_side\x18\x05 \x01(\t\"7\n\x13SetPositionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x12GetPositionRequest\x12\x10\n\x08\x61rm_side\x18\x01 \x01(\t\"i\n\x13GetPositionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rarm_positions\x18\x03 \x03(\x01\x12\x19\n\x11gripper_positions\x18\x04 \x03(\x01\">\n\x11InitializeRequest\x12\x13\n\x0b\x65nable_left\x18\x01 \x01(\x08\x12\x14\n\x0c\x65nable_right\x18\x02 \x01(\x08\"6\n\x12InitializeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x10\n\x0eTestRunRequest\"3\n\x0fTestRunResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcf\x03\n\x0eOpenArmService\x12\x45\n\nInitialize\x12\x1a.openarm.InitializeRequest\x1a\x1b.openarm.InitializeResponse\x12L\n\x0fGetLeftPosition\x12\x1b.openarm.GetPositionRequest\x1a\x1c.openarm.GetPositionResponse\x12L\n\x0fSetLeftPosition\x12\x1b.openarm.SetPositionRequest\x1a\x1c.openarm.SetPositionResponse\x12M\n\x10GetRightPosition\x12\x1b.openarm.GetPositionRequest\x1a\x1c.openarm.GetPositionResponse\x12M\n\x10SetRightPosition\x12\x1b.openarm.SetPositionRequest\x1a\x1c.openarm.SetPositionResponse\x12<\n\x07TestRun\x12\x17.openarm.TestRunRequest\x1a\x18.openarm.TestRunResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openarm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITION']._serialized_start=34
  _globals['_POSITION']._serialized_end=94
  _globals['_SETPOSITIONREQUEST']._serialized_start=97
  _globals['_SETPOSITIONREQUEST']._serialized_end=263
  _globals['_SETPOSITIONRESPONSE']._serialized_start=265
  _globals['_SETPOSITIONRESPONSE']._serialized_end=320
  _globals['_GETPOSITIONREQUEST']._serialized_start=322
  _globals['_GETPOSITIONREQUEST']._serialized_end=360
  _globals['_GETPOSITIONRESPONSE']._serialized_start=362
  _globals['_GETPOSITIONRESPONSE']._serialized_end=467
  _globals['_INITIALIZEREQUEST']._serialized_start=469
  _globals['_INITIALIZEREQUEST']._serialized_end=531
  _globals['_INITIALIZERESPONSE']._serialized_start=533
  _globals['_INITIALIZERESPONSE']._serialized_end=587
  _globals['_TESTRUNREQUEST']._serialized_start=589
  _globals['_TESTRUNREQUEST']._serialized_end=605
  _globals['_TESTRUNRESPONSE']._serialized_start=607
  _globals['_TESTRUNRESPONSE']._serialized_end=658
  _globals['_OPENARMSERVICE']._serialized_start=661
  _globals['_OPENARMSERVICE']._serialized_end=1124
# @@protoc_insertion_point(module_scope)
